### ISSUE TITLE
native ads

### ISSUE THREAD

**Issue by SodaSurfer** [adampax/MoPubSwiftUIDemo#1]
Hi, great project example, thanks a lot!

Do you plan to implement a native-ad example with swift as well? as it's a bit different from what I saw and I can't figure to how to implement it, and it looks like u r the only one on the web who did it lol

cheers and thanks again

**Comment by adampax** [comment]
Sorry, I don't have any plans to do a swift example. Yeah, it is a bummer that MoPub doesn't offer a swift tutorial.
