### ISSUE TITLE
reloading interstitial ad

### ISSUE THREAD

**Issue by SodaSurfer** [adampax/MoPubSwiftUIDemo#2]
Hi

I see you are creating a new interstitial ad every time a view is appearing:
```
.onAppear {
                self.interstitial = Interstitial()
            }
```
and therefore you create a new interstitial object every time.

wouldn't it be more accurate to create the interstitial only once in an `"init()"` method and then just to reload it every time an ad is dismissed?

**Comment by adampax** [comment]
Yes, you can do it however you like, though onAppear acts similar to an init in this case.
